create table if not exists questions (
  id bigint generated by default as identity primary key,
  name text not null,
  question_text text not null,
  answer text,
  vote_count integer not null default 0,
  status text not null default 'Pending',
  created_at timestamptz not null default now()
);

alter table questions enable row level security;

create policy "public can read questions"
on questions for select
to anon
using (true);

create policy "public can insert questions"
on questions for insert
to anon
with check (true);

create policy "public can update questions"
on questions for update
to anon
using (true)
with check (true);